apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kevin-costner-hpa
  labels:
    app: kevin-costner
    version: 0.0.1
    backstage.io/kubernetes-id: kevin-costner
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: kevin-costner
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75